### ISSUE TITLE
Error when I start

### ISSUE THREAD

**Issue by Cobe123** [Atterratio/pyIdleMasterReborn#1]
cody@cody-iMac:~/Documents/idle-bot-master$ python idle_bot.py
File "idle_bot.py", line 71
SyntaxError: Non-ASCII character '\xc2' in file idle_bot.py on line 71, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by Atterratio** [comment]
In requirements python 3, this error what you write standart for python 2.
